### ISSUE TITLE
slicing soundcloud link does not work

### ISSUE THREAD

**Issue by stefanschauer** [schollz/teoperator#8]
I tried to post a soundcloud link to get a drumkit as youtube-dl works for soundcloud links as well and I got this error message `ffmpeg; exit status 1 `
or
`open data/93ae0821057573cc0ca3bf2df687a127/metadata.json: no such file or directory`

OS: ubuntu
browser: firefox

thanks a lot for the work!

**Comment by schollz** [comment]
i think this should work now too!

**Comment by stefanschauer** [comment]
I tried again and got this error message:
Post "https://duct.schollz.com/zackzack123zackzack123": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
