### ISSUE TITLE
Slicing of mp3 does not work

### ISSUE THREAD

**Issue by stefanschauer** [schollz/teoperator#9]
When I post a mp3 to the website, I get redirected to a blank page. same issue for wavs

page url: https://op1z.com/patch?audioURL=https%3A%2F%2Fop1z.com%2Fdata%2Fuploads%2Fupload685124229Flatpack+-+808-153864891.mp3&secondsStart=0&secondsEnd=0&synthPatch=drum&removeSilence=no&rootNote=A

OS: ubuntu
Browser: Firefox

**Comment by schollz** [comment]
@stefanschauer thanks, can you try it again? I think i fixed it

**Comment by stefanschauer** [comment]
Thanks for your quick response! I tested it again. it worked once but the second time I got redirected to a blank screen again.

**Comment by stefanschauer** [comment]
I uploaded the aif that worked and the op1 says that it can't parsed.

**Comment by schollz** [comment]
Ahh oh no! Sorry for all these problems. I wonder whats changed. TBH I haven't used this in a couple months but back then it was working beautifully and I made dozens of samples.

Could you send me that aif and also the URL you got it from? You can email if you want: zack.scholl@gmail.com
